import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Analytics } from "@vercel/analytics/next";

import "./globals.css";
import { Bricolage_Grotesque } from "next/font/google";
import NextTopLoader from "nextjs-toploader";

import Footer from "@/components/Layout/Footer";
import Header from "@/components/Layout/Header";
import SessionProviderComp from "@/components/nextauth/SessionProvider";

const font = Bricolage_Grotesque({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Homely - A Real Estate Framer Template",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className="color-scheme-light dark:color-scheme-dark"
      data-scroll-behavior="smooth"
    >
      <body className={`${font.className} bg-white antialiased dark:bg-black`}>
        <NextTopLoader color="#07be8a" />
        <SessionProviderComp>
          <ThemeProvider attribute="class" enableSystem={true} defaultTheme="light">
            <Header />
            {children}
            <Footer />
          </ThemeProvider>
        </SessionProviderComp>
        <Analytics />
      </body>
    </html>
  );
}
