import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";

import "./globals.css";
import { Bricolage_Grotesque } from "next/font/google";
import NextTopLoader from "nextjs-toploader";

import Footer from "@/components/Layout/Footer";
import Header from "@/components/Layout/Header";

const font = Bricolage_Grotesque({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Homely - A Real Estate Framer Template",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className="color-scheme-light dark:color-scheme-dark"
      data-scroll-behavior="smooth"
    >
      <body className={`${font.className} bg-white antialiased dark:bg-black`}>
        <NextTopLoader color="#07be8a" />
        <ThemeProvider attribute="class" enableSystem={true} defaultTheme="light">
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
